require("config")
require("plugins")

vim.cmd("set number")
vim.cmd("set rnu")
vim.cmd("noremap C-Bs> db")
vim.cmd("noremap <C-del> dw")
vim.cmd("noremap <BS> dh")
vim.cmd("set scrolloff=4")
vim.cmd("set tabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set softtabstop=2")
vim.cmd("set expandtab")
vim.cmd("set autoindent")
vim.cmd("set ignorecase")
vim.cmd("set smartcase")
vim.cmd("syntax on")
vim.cmd("set mouse=a")
vim.cmd.colorscheme("gruvbox")
