local illuminate = require("illuminate")

vim.keymap.set("n", "<M-n>", function()
  require("illuminate").goto_next_reference()
  vim.api.nvim_feedkeys("zz", "n", true)
end)
vim.keymap.set("n", "<M-p>", function()
  require("illuminate").goto_prev_reference()
  vim.api.nvim_feedkeys("zz", "n", true)
end)

vim.keymap.set({ "v", "x" }, "<A-n>", function()
  illuminate.goto_next_reference()
  vim.api.nvim_feedkeys("zz", "n", true)
end)
vim.keymap.set({ "v", "x" }, "<A-p>", function()
  illuminate.goto_prev_reference()
  vim.api.nvim_feedkeys("zz", "n", true)
end)
