local illuminate = require("illuminate")

-- TODO: Refer to goto_next_reference() to see why centering is working here but not gd/gi
vim.keymap.set("n", "<M-n>", function()
  require("illuminate").goto_next_reference()
  center_screen()
end)
vim.keymap.set("n", "<M-p>", function()
  require("illuminate").goto_prev_reference()
  center_screen()
end)

vim.keymap.set({ "v", "x" }, "<A-n>", function()
  illuminate.goto_next_reference()
  center_screen()
end)
vim.keymap.set({ "v", "x" }, "<A-p>", function()
  illuminate.goto_prev_reference()
  center_screen()
end)
